### ISSUE TITLE
Duden workflow is not working with Alfred 3.8.1

### ISSUE THREAD

**Issue by tsologub** [deanishe/alfred-duden#4]
Is it only me facing the issues with Duden workflow?
Since yesterday it stopped working. 

Alfred version: v3.8.1 (961)
Duden workflow version: 1.4

[example](https://imgur.com/hN5hM9r)

**Comment by deanishe** [comment]
> Is it only me facing the issues with Duden workflow?

Nope. Doesn't work for me, either. I haven't had a chance to look into it yet, but I'd guess they've changed the HTML and thus broken my parser. (I'm surprised it's taken this long to break, tbh.)

I'll look into it in the next couple of days and see if I can get it working again.

**Comment by nikitavoloboev** [comment]
Alternatively one can use https://github.com/alexander-heimbuch/linguee-alfred-workflow

I think it does the same thing as this workflow and faster. I don't speak german so maybe mistaken.

**Comment by TyLeRRR** [comment]
> Alternatively one can use https://github.com/alexander-heimbuch/linguee-alfred-workflow
> I think it does the same thing as this workflow and faster. I don't speak german so maybe mistaken.

Nikita, thanks for the tip.
My use case for the Duden workflow is that I always mix up the correct articles (der, die, das) for some nouns. So the Duden workflow comes in handy. Sadly I haven't found this feature in Linguee. But nevertheless, I think it is a good alternative.

**Comment by deanishe** [comment]
> I always mix up the correct articles (der, die, das)

For that particular use case, [this workflow is pretty good](https://github.com/ignazioc/DerDieDas). It takes some setting up (you need to request a copy of the dict.cc dictionary), but after that it's offline, so it works very fast. The downside is that it's *huge* (well over 100MB) once the dictionary is installed.

**Comment by deanishe** [comment]
@TyLeRRR I deleted Niki's mindless comment, but GitHub seems to have deleted yours with it (perhaps because it quoted him?) Sorry. That wasn't intentional.

**Comment by tsologub** [comment]
@deanishe no, I have deleted my comment by myself. Niki's and my comments weren't related to this bug. So I just decided to keep it clean. It's fine.

**Comment by deanishe** [comment]
Well, that was a lot easier than expected. Fixed in [v1.5.0](https://github.com/deanishe/alfred-duden/releases/tag/v1.5.0). Grab it from the link or enter `duden workflow:update` in Alfred.

**Comment by deanishe** [comment]
> Niki's and my comments weren't related to this bug.

Neither's the one I made now. I guess I'd better delete the others (and this one) a bit later, too.

**Comment by nikivdev** [comment]
Delete this confused comment too. I genuinely thought my suggestion would be relevant to OP. Maybe not relevant to fixing the bug but still relevant. Open source is tough business.

**Comment by deanishe** [comment]
> I genuinely thought my suggestion would be relevant to OP

Why did you think that, Niki? You certainly didn't bother to ask OP what he wanted, and if you'd spent even a few seconds looking at the README, you'd have noticed that this workflow is for a **monolingual** dictionary, and thus not the same thing as the Linguee one. No knowledge of German required.

And as you don't speak German, why are you recommending German stuff? How do you know if the Linguee workflow you recommended is actually any good?

Except you don't care about "good", do you? Just "fast". Doesn't matter if it's good or correct or relevant or useful. As long as it's fast.

And that's why I deleted your comment. Not because it wasn't relevant, but because you just shat the first thing that came into your head into the thread without thinking, as you usually do.

> Open source is tough business.

No it isn't. You're hard work and I'm a dick.

**Comment by nikivdev** [comment]
Fair enough. I did actually try the Linguee workflow and it seemed both good and fast. And I do care about both fast and good. 

> workflow is for a **monolingual** dictionary

I did look at readme and somehow didn't see that it was. Should of paid attention to the GIF.

> but because you just shat the first thing that came into your head into the thread without thinking, as you usually do

That explains it and is fair. 


> Why did you think that, Niki?

Because I didn't realize this workflow was monolingual. I did learn a new word today so that's nice. 🙂

**Comment by nikivdev** [comment]
> Except you don't care about "good", do you? Just "fast"

And.. I mean I have workflows of my own you know. All of them are fast. But also useful. I think.

**Comment by deanishe** [comment]
> I did look at readme and somehow didn't see that it was. Should of paid attention to the GIF.

That's *exactly* what I mean.

> And.. I mean I have workflows of my own you know.

I wasn't really talking about workflows.

**Comment by nikivdev** [comment]
To my defence german does look similar to english. So similar I might learn it one day. 🌿

**Comment by deanishe** [comment]
> german does look similar to english

They share an alphabet… Russian doesn't have articles, right? Well, German has 16 words for "the" and 12 for "a/an".

Still, if you speak ~~swamp German~~ Dutch, it should be fairly familiar.

**Comment by nikivdev** [comment]
> Russian doesn't have articles, right?

It doesn't. But it has complex rules of [Declension](https://en.wikipedia.org/wiki/Declension). 

And I don't speak dutch nor plan to learn it. 

The only human language I was thinking of learning was Japanese (for broadening my mind). And Germany is a nice country I might move to in future so might as well learn their language.

**Comment by nikivdev** [comment]
> Well, German has 16 words for "the" and 12 for "a/an".

Maybe not german then 😅

I read that you don't really need to know german to live a normal life in Berlin at least (assuming I find a place).
